services:
  db:
    image: mysql:latest
    container_name: entrevistas-maricultura-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    #image: redis/redis-stack-server
    image: redis/redis-stack
    container_name: acess-token-maricultura
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"