services:
  db:
    image: mysql:latest
    container_name: entrevistas-maricultura-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      #- db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./db/my.cnf:/etc/mysql/my.cnf

#volumes:
#  db_data:
